# Bash...
# BashRC...
[[ -f $HOME/.bashrc ]] && source $HOME/.bashrc
# User PATH...
[[ -d $HOME/bin/ ]] && export PATH=$HOME/bin/:$PATH # After...
#[[ -d $HOME/bin/ ]] && export PATH=$PATH:$HOME/bin/ # Before...
# Start Xorg...
[[ $EUID != 0 && $(tty) = "/dev/tty1" ]] && exec startx
[[ $EUID != 0 && $(tty) = "/dev/tty3" ]] && exec startx
[[ $EUID != 0 && $(tty) = "/dev/tty5" ]] && exec startx
